[package]
name = "taxy-webui"
version = "0.1.0"
edition = "2021"

[dependencies]
yew = { version = "0.20", features = ["csr"] }
wasm-bindgen = "0.2"
ybc = "0.4.0"
console_error_panic_hook = "0.1.7"
gloo-console = "0.2.3"
yew-router = "0.17.0"
gloo-net = "0.2.6"
wasm-bindgen-futures = "0.4.36"
taxy-api = { path = "../taxy-api" }
serde_json = "1.0.96"
gloo-utils = "0.1.6"
serde_derive = "1.0.163"
serde = "1.0.163"
serde-wasm-bindgen = "0.5.0"
yewdux = "0.9.3"
web-sys = "0.3.63"
futures = "0.3.28"
